### ISSUE TITLE
Missing file or dir

### ISSUE THREAD

**Issue by MrFlyingToasterman** [xc0d3rz/metasploit-apk-embed-payload#15]
**It seems like the Programs cant find a file called payload.apk
But the dir /tmp/NJTYNVC/ is created with a original/ dir and a original.apk in it.**

```
[2] Signing payload
java.io.FileNotFoundException: /tmp/NJTYNVC/payload.apk (Datei oder Verzeichnis nicht gefunden)
  at java.util.zip.ZipFile.open(Native Method)
  at java.util.zip.ZipFile.<init>(ZipFile.java:219)
  at java.util.zip.ZipFile.<init>(ZipFile.java:149)
  at java.util.jar.JarFile.<init>(JarFile.java:166)
  at java.util.jar.JarFile.<init>(JarFile.java:145)
  at com.android.signapk.SignApk.main(SignApk.java:320)
```

**Another exception in step 4**

```
[4] Decomposing payload APK
Input file (/tmp/NJTYNVC/signapk.apk) was not found or was not readable.
```

**And a final one in step 7**

```
[7] Loading MainActivity.smali and injecting payload
lib/embed-payload.rb:79:in initialize: No such file or directory @ rb_sysopen - /tmp/NJTYNVC/payload/AndroidManifest.xml (Errno::ENOENT)
  from lib/embed-payload.rb:79:in open
  from lib/embed-payload.rb:79:in fixManifest
  from lib/embed-payload.rb:246:in embeddingPayload
  from lib/embed-payload.rb:11:in initialize
  from apk-embed-payload.rb:30:in new
  from apk-embed-payload.rb:30:in <main>
```

_I guess it depends on signing.
Im useing Arch GNU/Linux with ruby 2.3 & OpenJDK 1.8.2 (64 Bit)_

**Comment by 0vulns** [comment]
Do you have metasploit framework ?

2016-10-06 13:53 جرينتش-04:00, Darius Musiolik notifications@github.com:

**Comment by MrFlyingToasterman** [comment]
@xc0d3rz Yes i have the current Version installed. 
I tryed it as super and norm user but i got the same error Message.
Just in case i runned a `gem update` but this does not work to.
