### ISSUE TITLE
Many Problems

### ISSUE THREAD

**Issue by sasatefa2009** [xc0d3rz/metasploit-apk-embed-payload#29]
First:-
```
[2] Signing payload
java.io.FileNotFoundException: /tmp/K7X9X9K/payload.apk (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:145)
	at com.android.signapk.SignApk.main(SignApk.java:320)

```
Second: Third Phase is full of this

[3] Decomposing original APK
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000055
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000001a
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000055
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000001a
W: Could not decode attr value, using undecoded value instead: ns=android, name=installLocation, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000007
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x00000015
W: Could not decode attr value, using undecoded value instead: ns=android, name=anyDensity, value=0xffffffff

**and ends with this** 

```
Exception in thread "main" brut.androlib.AndrolibException: java.io.FileNotFoundException: /root/.local/share/apktool/framework/1.apk (No such file or directory)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:588)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:121)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:83)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:73)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
	at brut.androlib.res.data.value.ResBagValue.serializeToResValuesXml(ResBagValue.java:42)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:517)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.FileNotFoundException: /root/.local/share/apktool/framework/1.apk (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:584)
	... 14 more
```

Third:-

```
[4] Decomposing payload APK
Input file (/tmp/K7X9X9K/signapk.apk) was not found or was not readable.
```

Fourth:-

```
[5] Locating onCreate() hook
lib/embed-payload.rb:215:in `embeddingPayload': undefined method `gsub' for 0:Integer (NoMethodError)
	from lib/embed-payload.rb:11:in `initialize'
	from apk-embed-payload.rb:30:in `new'
	from apk-embed-payload.rb:30:in `<main>'
```

**Comment by 0vulns** [comment]
Hi, it seem to you don't have installed metasploit framework

**Comment by sasatefa2009** [comment]
@xc0d3rz  I'm on kali linux 2017.1 fully updated

**Comment by stafordtituss** [comment]
I have the same problem!!!! ☹️

**Comment by stafordtituss** [comment]
Please help!!
